/**
 * Created by kyle on 9/19/17.
 */
export default (function(){
    return({
        CREATE_COURSE: 'CREATE_COURSE',
        LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
        LOAD_COURSES_FAILURE: 'LOAD_COURSES_FAILURE',
        LOAD_COURSE_THREADS_SUCCESS: 'LOAD_COURSE_THREAD_SUCCESS',
        LOAD_COURSE_THREADS_FAILURE: 'LOAD_COURSE_THREAD_FAILURE',
        LOAD_THREAD_POSTS_SUCCESS: 'LOAD_THREAD_POSTS_SUCCESS',
        LOAD_THREAD_POSTS_FAILURE: 'LOAD_THREAD_POSTS_FAILURE',
        CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
        CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
        START_AJAX_CALL: 'START_AJAX_CALL'
    });
})();